version: "3.8"
services:
  calc-serverless:
    depends_on:
      - dynamodb
      - memcached
      - dynamodb-init
    image: amazon/aws-sam-cli-build-image-nodejs12.x
    hostname: calc-serverless
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "~/.aws:/root/.aws"
      - "$DOCKER_VOLUME_BASEDIR:$DOCKER_VOLUME_BASEDIR"
    networks:
      calc:
    command: "$DOCKER_VOLUME_BASEDIR/run.sh --docker-volume-basedir $DOCKER_VOLUME_BASEDIR --docker-network calc_calc --profile local --region us-east-1 --env-vars env.json --host 0.0.0.0 --container-host host.docker.internal --warm-containers EAGER"
        
  calc-ui-web:
    image: calc-ui-web
    hostname: calc-ui-web
    build:
      context: ../calc-ui-web/.
    ports:
      - 5000:5000
    networks:
      calc:

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb
    ports:
      - 8000:8000
    networks:
      calc:
    command: ["-jar", "DynamoDBLocal.jar"]

  dynamodb-init:
    depends_on:
      - dynamodb
    image: amazon/aws-cli
    hostname: dynamodb-init
    volumes:
      - "./.local-env/dynamodb/.aws:/root/.aws"
    networks:
      calc:
    command: >
      dynamodb create-table
        --table-name Calculators
        --attribute-definitions AttributeName=id,AttributeType=S
        --key-schema AttributeName=id,KeyType=HASH
        --endpoint-url http://dynamodb:8000
        --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1

  memcached:
    image: memcached
    hostname: memcached
    ports:
      - 11211:11211
    networks:
      calc:

networks:
  calc:
